### ISSUE TITLE
Upgrade commons-text to 1.10.0 due to CVE-2022-42889

### ISSUE THREAD

**Issue by Ironlink** [jknack/handlebars.java#1009]
See https://nvd.nist.gov/vuln/detail/CVE-2022-42889

I tried to build the project locally to see if there were any compatibility issues. I can build and test `Handlebars.java`, and I can compile but not test the next module `Handlebars`. Tests fail because I don't have a JDK old enough to support Nashorn (removed in JDK 15).

**Comment by svettwer** [comment]
Seems like it's a more complicated fix, because the vulnerability is shaded into a internal package here https://github.com/jknack/handlebars.java/blob/master/handlebars/pom.xml#L46-L49

**Comment by xercasy** [comment]
Hello, this issue will be fixed quickly ? thx

**Comment by aschwarte10** [comment]
We are a happy user of the Handlebars library. The current version of handlebars appears in different vulnerability scanners due to the above mentioned CVE.  

We have provided a PR in https://github.com/jknack/handlebars.java/pull/1010 that updates the commons-text dependency to the latest non-affected version.

Would be great to see a new version of handlebars.java being published soon

**Comment by jknack** [comment]
I will review, merge and release in the following days.

Thanks.

**Comment by svettwer** [comment]
It seems like PR https://github.com/jknack/handlebars.java/pull/1010 upgrades the dependency but does not remove the shaded copy which is dead code as far as I can see.
I'll propose another PR removing this as well.

**Comment by jknack** [comment]
@svettwer I will do it.

**Comment by svettwer** [comment]
Ah, just raised the PR! :smile: 
Feel free to close it if you already did it.

**Comment by jetztgradnet** [comment]
> So CVE scanners might react on that as well, depending on their implementation.

They do, that's why @aschwarte10 created the PR to update the dependency... 

That's the problem with shaded dependencies. I understand why they exist, but they are hidden and make dependency management and copying with vulnerabilities really difficult

**Comment by jknack** [comment]
@svettwer don't we just need to update the dependency?

Shade plugin will use the new library.

**Comment by jetztgradnet** [comment]
It will, so the merged PR satisfies the (minimal) requirement for the update already.

But when it is shaded, it's baked in. If it was only a regular dependency like Jackson or others, everybody could simply just update their own dependencies in the respective application without any code changes in the handlebars library and it would not be as urgent and requiring your time and attention...

**Comment by jetztgradnet** [comment]
Same actually for Commons Lang3 and Antlr. 

Antlr is shaded quite often because of how it works with different Java versions, but even then ideally there would be no need for shading anything.

But simply removing shading might make the library backwards incompatible, as now these dependencies are required and need to be provided by an application, so this might actually rather be something for a 4.4 or 5.0 release. 
(Although I certainly wouldn't mind having this removed now already, because we explicitly manage all dependencies anyway and don't rely on transitive dependencies ;-) )

**Comment by jknack** [comment]
are all you OK to removed shaded dependencies? If so, I can plan to remove them in 5.x (and requires Java 11 at minumum)

**Comment by jetztgradnet** [comment]
yes, getting rid of shaded libraries would be great!

Thanks for looking into this, @jknack!

**Comment by svettwer** [comment]
>But simply removing shading might make the library backwards incompatible, as now these dependencies are required and need to be provided by an application, so this might actually rather be something for a 4.4 or 5.0 release.

This might be the case for Lang3 and Antlr. There I did no investigation. For commons-text, it should work, because we only updated from 1.9 to 1.10.0 anyways. There was no big jump in versioning.  

>are all you OK to remove shaded dependencies? If so, I can plan to remove them in 5.x (and requires Java 11 at minumum)
Yeah, would work for me as well!

Thanks @jknack for your quick reaction on this! :hugs: :heart:

**Comment by jetztgradnet** [comment]
> For commons-text, it should work, because we only updated from 1.9 to 1.10.0 anyways. There was no big jump in versioning.

the problem is not the version bump, but that right now (with 4.3.0) you can just use handlebars as-is without providing commons-text. When removing the shaded library, you would need to add this to your list of dependencies as it is no longer provided by the library internally... so an application using handlebars might break after updating to say 4.3.1 (at least when disabling transitive dependencies in Gradle as we do)

**Comment by svettwer** [comment]
Oh, good catch! Sure, did not think about that. :+1:

**Comment by jknack** [comment]
Pushed 4.3.1 to central will be available shortly.

**Comment by aschwarte10** [comment]
Also from my side, thanks 👍  @jknack
