### ISSUE TITLE
java modules: modularize handlebars modules

### ISSUE THREAD

**Issue by jknack** [jknack/handlebars.java#1018]

**Comment by agentgt** [comment]
@jknack is there any chance you can pump out a release with at least Automatic-Module-Name ?

I need this kind of badly for our general conversion to Jooby 3.0

**Comment by agentgt** [comment]
Or I can put in a PR if you like?

**Comment by Montimur** [comment]
@jknack, any updates on this enhancement? I am currently unable to modularize my application because I use WireMock, which in turn uses handlebars and handlebars-helpers. This causes a compilation error:
`[ERROR] module wiremock reads package com.github.jknack.handlebars.helper from both handlebars.helpers and handlebars`

It's important that I get this resolved, soon. I could lend a hand, if so desired, to modularize this code. I image renaming the above packages would be a breaking change for many users, but I believe it will need to be done to complete this enhancement.

**Comment by agentgt** [comment]
@jknack I put in a PR on the 4.x branch to try to make it as easy as possible.

**Comment by jknack** [comment]
hey guys, I don't have time to work on this yet... but I feel we should truly write modules not just adding the manifest entry.

**Comment by agentgt** [comment]
I agree. I just wanted to help @Montimur and others that can't wait.

I can possibly do a module-info PR in master but maybe there is more work that you want to do prior (e.g. refactoring)?

**Comment by jknack** [comment]
right, requires a bit more (cleanup mainly). Next release should be "modern JVM friendly", nothing more.
