### ISSUE TITLE
Traversing template context's with ../ implemented differently than handlebars.js

### ISSUE THREAD

**Issue by am80l** [jknack/handlebars.java#356]
Related to https://github.com/jknack/handlebars.java/issues/329

I believe 329 was incorrectly fixed, and I take most of the blame for improper wording/misunderstanding of the issue. wycats answer to this issue on handlebars.js https://github.com/wycats/handlebars.js/issues/196 clarifies the issue : 

> In Handlebars, each template has a context. Blocks ({{#if foo}}) create inline templates, and the helper (if) decides what context to render the template in.

> Some helpers preserve the current context (like if), while others change it in different ways (each and with, for example). Helpers can even change the context to something totally new if they want (options.fn({ zomg: true })).

> The .. feature means "look this up on the context of the parent template". In some cases, that will amount to the parent in the current object (with). In other cases, it will not. In cases like if, which preserve the context, .. will happen to point to the same object, but this is just a coincidence.

> In all cases, .. is lexically bound to the parent template.

So given the following nested conditional, getting outside the each would require a ../../ in this example, regardless of whether or not the "if" block creates a context:

<pre>
{{#each obj.props}}
     {{#if obj.props}}
         {{../../this}}
     {{/if}}
{{/each}}
</pre>

So  https://github.com/jknack/handlebars.java/issues/329 partially fixed this issue, since now the above code should render similarly in handlebars java and js. The root issue though remains which is that handlebars java is implementing the ../ syntax incorrectly. 

Prior to the fix of https://github.com/jknack/handlebars.java/issues/329 this was the behavior, and the issue that should have been addressed:

<pre>
{{#each obj.props}}
     {{#if obj.props}}
         {{../this}}
         {{this}}
     {{/if}}
{{/each}}
</pre>

Using this example in handlebars.js, "this" and "../this" refers to the same thing (intended behavior) since the "../" simply means "look in the parent template's context". In handlebars java, "../this" actually would incorrectly refer to the root context. It seems Handlebars Java is climbing up the context rather than looking in the paren't template's context. Handlebars Java should handle context traversal in the same way as handlebars.js to maintain template portability.

Please let me know if you would like a more detailed example or more details on the issue.

Thanks!

**Comment by jknack** [comment]
yea I'm not sure what the issue is...

In handlebars.java ../ means look at the parent context, not in the root context as you said.

Please add a example of templates, data and expected output but also make sure to add the expected behaviour for #329

Thanks

**Comment by am80l** [comment]
I only meant it referred to the root context in the given example, not in general, my apologies for being unclear.

     {{#each obj.props}}
          {{#if obj.props}}
              {{../this}}
              {{this}}
          {{/if}}
     {{/each}}

in Handlebars.js "../" is used to traverse templates, not context. It means "look at the parent template, now use that context". This is different from handlebars.java which uses "../" to traverse context. Nested templates or helpers may have the same context depending on how that helper is written. In the above example "../this" and "this" refer to the same context, because {{if}} does not create context.

**Comment by tankchintan** [comment]
Looks like we are also facing the same issue. 

Here is the data,
```JavaScript
{
    trayType: "video",
    data: {
        items: [{id: "id-1", "name": "name-1"}], 
        config: {}
    }
}
```

Here is the template,
```
{{#each data.items}}
   1111:  {{trayType}} 
   2222:  {{../trayType}}
   3333:  {{../../trayType}}
    {{#if imageOverridden ~}}
        image-overridden
    {{else ~}}
        {{#if ../../trayType ~}}
            size-{{../../trayType}}
        {{~/if}}
    {{~/if}}    
{{/each}}
```

Now here the expected output (when rendering through Handlebars.JS) is,
```
1111:  //empty because currently we are in data.item, & there is no trayType property for a single item
2222:  //empty because currently we are in data.item, so this would take us one level up. i.e in data
3333:  video
```

**Comment by jknack** [comment]
a lot of things are wrong here, one or the most important is: that handlebars.js isn't 100% compatible with the [mustache spec](https://github.com/mustache/spec/tree/master/specsz) while handlebars.java is 100% compatible.

```
1111 {{trayType}}
```
mustache spec said that if a var isn't available in the current context: **It should check the parent context**, from here there are two outputs: **variable exists in the parent** or **we reach the root level and variable isn't present**

```
2222 {{../trayType}}
```
same problem as 1111. Handlebars.java doesn't find the var in the parent: **../** so it ask to the parent of the parent (mustache spec) and got it.

```
3333 {{../../trayType}}
```
here is a difference (again) on how **context** was implemented handlebars.js vs handlebars.java. In handlebars.java the expression ```data.items``` was resolved as a unit or single value, while in handlebars.js seems to split the expression in two ```data``` and ```items``` but it only assigns a context to the first of them ```data```. Then js/java assign a new context per iteration/item. That's why you go an extra level in handlebars.js but not in handlebars.java. In my understanding of the mustache spec, handlebars.js should NOT create a new context for ```data``` the context is required per iteration (item in your case).

To be honest? none of these are real bug for me and it is the result of handlebars.java being 100% compatible with the mustache spec while handlebars.js isn't

So, how can you fix/workaround this?

1111/2222 are fixed it in both by using the ```this.``` qualifier. ```this.``` will scope the lookup to the current context and stop if the value isn't there.

3333 think can be fix it by introducing a new context for data. ```#{{data}}``` or ```{{#with data}}``` will introduce a new context and the lookup will work as you expect

```
{{#data}}
{{#each items}}
   1111:  {{this.trayType}} 
   2222:  {{../this.trayType}}
   3333:  {{../../trayType}}
    {{#if imageOverridden ~}}
        image-overridden
    {{else ~}}
        {{#if ../../trayType ~}}
            size-{{../../trayType}}
        {{~/if}}
    {{~/if}}    
{{/each}}
{{/data}}
```

I didn't try this in handlebar.js but 99% sure it works too

**Comment by tankchintan** [comment]
@jknack Thanks for the detailed response!

I am checking your suggestions out. In the meantime, could you tell me why {{@root}} works in javascript but not in java?

**Comment by jknack** [comment]
it is probably a new feature in handlebars.js that I'm not aware

**Comment by tankchintan** [comment]
So we switched to your idea of 
```
{{#with data}}
{{#each items}}
```
And this gives us much more predictable & consistent output when rendered via java & javascript.

Also yeah, @root is new in handlebars.js v2.0.

**Comment by jknack** [comment]
cool, can you raise a new issue about adding ```@root```?

**Comment by tankchintan** [comment]
Done. see https://github.com/jknack/handlebars.java/issues/385
