### ISSUE TITLE
evaluate changing the return type of Helper from CharSequence to Object

### ISSUE THREAD

**Issue by jknack** [jknack/handlebars.java#484]
Think is time to change the return type of Helper from CharSequence to Object...

We need to evaluate how big the change is and what is affected... personally don't think is a huge change but need to review it closely.

This change will improve handlebarsjs compatibility and fix #483

**Comment by chli1** [comment]
I already had a quick look at this issue.

Changing the method signature `CharSequence Helper.apply(T context, Options options)` to `Object Helper.apply(T context, Options options)` and make the `RhinoHandlebars` wrapper return other objects than CharSequence is indeed easy. But the change is not sufficient for e.g. passing a Boolean from a sub expression to the `IfHelper`, because the `apply()` and `merge()` methods from the `Template` and `BaseTemplate` objects will convert the return value from Boolean to String before passing it to the IfHelper.

So the whole `Template` interface have to be refactored, too. Without knowing this project very well it seems to me that this has a large overall impact.
