### ISSUE TITLE
context in js is different from context in java 

### ISSUE THREAD

**Issue by KurobaZhang** [jknack/handlebars.java#492]
context in each helper can get context in parent node.

**Comment by jknack** [comment]
please add an example with template and data.

thanks

**Comment by jfbrennan** [comment]
I assume @KurobaZhang is referring to this:

"That is because Handlebars.js doesn't look in the context stack for missing attributes in the current scope (this is consistent with the Mustache Spec).

Hopefully, you can turn-off the context stack lookup in Handlebars.java by qualifying the attribute with this.:"

`Hello {{#child}}{{this.value}}{{/child}}`

It would make more sense to me (and make sharing templates easier) if Handlebars.java was consistent with handlebars.js in this regard, since after all this is Handlebars.java and not Mustache.java. Parity with handlebars.js would make sense here...

**Comment by mAAdhaTTah** [comment]
In this case, I'd actually prefer the Java Mustache lookup, and you can have Handlebars.js do it by passing in the `compat` flag during compilation: http://handlebarsjs.com/reference.html
