### ISSUE TITLE
global property "size" overwrites local {{size}} 

### ISSUE THREAD

**Issue by erotte** [jknack/handlebars.java#552]
Problem:
When passing `size` as a local variable to a Handlebars partial, it is replaced with the current size/length of the root object.

e.g. 
    
    {{~> button size='large'}}  

button.hbs:

    <button class="button-{{size}}>
        Button with size {{size}}
    </button>

will render the following HTML
  
    <button class="button-8>
        Button with size 8
    </button>

I'm  not very familar with java, but this behavior may be related to:

https://github.com/jknack/handlebars.java/blob/master/handlebars-jackson2/src/main/java/com/github/jknack/handlebars/JsonNodeValueResolver.java#L143

Is `size` really essential here? 

The problem does not occur in the Javascript Implementation of Handlebars (4.0.4).  
 
regards,
Ecki

**Comment by JonasHavers** [comment]
I can confirm this issue. Having a Spring Boot setup with the following application yaml configuration, there is a global `size` context attribute.

```
handlebars:
  enabled: true
  resolver:
    field: true
    map: true
    java-bean: false
    method: false
```

The problem is that the `FieldValueResolver` picks up the field 'size' of the root HashMap (Spring MVC's ModelMap, i.e. an LinkedHashMap) and resolves the size of the map which is the number of key-value mappings.

A workaround for @erotte's example is to pass an explicit context attribute to the partial. 
```
{{~> button buttonContext}} 
```
With `buttonContext` representing a DTO in the root HashMap containing a `size` field and the value 'large'.

```
class ButtonContextDto {
  public String size;
}
```
```
ButtonContextDto dto = new ButtonContextDto();
dto.size = "large";
modelMap.addAttribute("buttonContext", dto);
```

**Comment by erikahlswede** [comment]
We are running into this same issue. Any word?  The given workaround will not work in our case.

**Comment by jknack** [comment]
This is how FieldValueResolver works. Still for such use case, all you need to do is to move `MapValueResolver` before `FieldValueResolver`
