### ISSUE TITLE
Default content of a partial doesn't work

### ISSUE THREAD

**Issue by blolg** [jknack/handlebars.java#613]
Hi! I'm trying to define default content of a partial if it is not found. I use the following syntax: 
```
{{#> myPartial }}
  Failover content
{{/myPartial}}
```

But I get the error "The partial 'myPartial' could not be found".

**Comment by jknack** [comment]
That doesn;t look right. You need `inline`:

```
{{#*inline "myPartial"}}
  Failover content
{{/inline}}
```

**Comment by cwadrupldijjit** [comment]
I know this issue is ancient and therefore likely requires a new issue made, but it looks like this is asking one thing and the answer is not correct.

According to https://handlebarsjs.com/guide/partials.html#partial-blocks (the JS portion of this), the partial blocks are meant to work where "Failover content" exists when the partial can't be found.  It might also allow for the contents of the partial block to be passed into the partial if desired/referenced with `{{> @partial-block}}`.

The `{{#*inline "foo"}}` thing is to define an inline partial, which might be used in the `{{> PARTIAL}}` way.  The failover content between the opening and closing tags of the partial block is separate and distinct.

The referenced documentation explains it fairly well.  If it's meant to be a complete port of the JS library, it would be wonderful if we can get the failover content as seen in the documentation to work.  Seeing as that was also not referenced in the readme or other documentation for this Java port, I don't think that this has been addressed yet.

If you want me to open a new issue to bring this into the Java version, I can do that, but my comment here was mostly meant to double-check my understanding of this issue and if the discrepancy is intentional.

**Comment by cwadrupldijjit** [comment]
Okay, I've reviewed the code and it seems like it does work the way that the JS version of Handlebars works, though it's not acknowledged anywhere I could find.  Regardless, what I pointed out about the difference in understanding holds true.

**Comment by jknack** [comment]
you're right. can you file a new bug?
